theme = "tokyonight"

[editor]
bufferline = "always" # show tab bar
mouse = true
end-of-line-diagnostics = "hint"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar" # when in insert mode show a bar instead of select block
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"  # show warnings and errors on the cursor lines

[keys.normal]
C-x = ":qa"
C-s = ":w!" # save
C-w = ":buffer-close" # close window
C-v = [":clipboard-paste-before"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"] # lazygit
C-d = ["move_prev_word_start", "move_next_word_end", "search_selection", "extend_search_next"] # multiselect
# d = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
# D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"] # select entire line rather than just from cursor
esc = ["collapse_selection", "keep_primary_selection"]
y = [":clipboard-yank", "yank"] # copy to system clipboard

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
# D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
# k = ["extend_line_up", "extend_to_line_bounds"]
# j = ["extend_line_down", "extend_to_line_bounds"]

[keys.insert]
C-z = "undo" # ctlr-z to undo
C-s = [":w!", "normal_mode" ] # save while in insert mode then go to normal mode
C-w = ":buffer-close" # close window
C-v = [":clipboard-paste-before"] # paste

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "spacer",
  "separator",
  "read-only-indicator",
  "file-modification-indicator",
]

center = []
right = [
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "total-line-numbers",
  "position-percentage",
  "file-encoding",
  "file-type"
]
separator = "â”‚"
